# Generated by Django 6.0.5 on 2026-05-27 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='包裹简述')),
                ('description', models.TextField(blank=True, default='', verbose_name='详细描述')),
                ('location', models.CharField(choices=[('nanmen', '南门快递柜'), ('beimen', '北门快递站'), ('cainiao', '菜鸟驿站'), ('yunda', '韵达快递点'), ('shunfeng', '顺丰快递点'), ('jindong', '京东快递点'), ('other', '其他')], max_length=20, verbose_name='快递点')),
                ('pickup_code', models.CharField(blank=True, default='', max_length=50, verbose_name='取件码')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='报酬金额')),
                ('contact', models.CharField(max_length=50, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('pending', '待接单'), ('accepted', '已接单'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helped_orders', to=settings.AUTH_USER_MODEL, verbose_name='接单者')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_orders', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
