# Generated by Django 6.0.5 on 2026-05-27 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.CharField(default='bi-shop', max_length=50, verbose_name='Bootstrap图标类名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '美食分类',
                'verbose_name_plural': '美食分类',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('image', models.ImageField(default='shops/default.jpg', upload_to='shops/', verbose_name='店铺图片')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('avg_price', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='人均价格')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='评分')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food.shop', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '用户评价',
                'verbose_name_plural': '用户评价',
                'ordering': ['-created_at'],
            },
        ),
    ]
