# Generated by Django 6.0 on 2026-06-12 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['shop', 'user'], name='food_review_shop_id_037cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='food_review_rating_c5aefa_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['name'], name='food_shop_name_978f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['category'], name='food_shop_categor_8a2f93_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['-created_at'], name='food_shop_created_86de7d_idx'),
        ),
    ]
